### ISSUE TITLE
First day of the week setting not saved

### ISSUE THREAD

**Issue by bogenschlag** [TfTHacker/obsidian42-jump-to-date#11]
<img width="652" alt="image" src="https://user-images.githubusercontent.com/5374341/188895174-056eba53-1b3c-4559-aa74-01aa58b30712.png">

I constantly have to the first day of the week to Monday, again, every time I open Obsidian.

Am I holding it wrong? 😉

**Comment by TfTHacker** [comment]
This is now fixed. Thank you for taking the time to report it. Just to update in Obsidian Community plugins.

I think you were holding it just fine ☺️ rather developer bug ☺️
