### ISSUE TITLE
Doesn't display date picker on Android with Obsidian 1.4.0

### ISSUE THREAD

**Issue by thephm** [TfTHacker/obsidian42-jump-to-date#13]
Android 12
Obsidian 1.4.0

Steps
1. Press and hold the navigation button on the far bottom right
2. Choose Jump to date button

Expected result: see date picker 📅

Actual result: nothing happens :(![20221021_064453.jpg](https://user-images.githubusercontent.com/8527588/197178640-033ad9ce-fbe8-41d7-8603-d13b4577b92a.jpg)

**Comment by TfTHacker** [comment]
Thank you for your report. I attempted a fix, would appreciate if you can confirm if it works on Android. I am on iOS.

**Comment by thephm** [comment]
Works! I had to restart Obsidian first. Thanks so much for the quick turnaround, woohoo!![Screenshot_20221021-110854_Obsidian.jpg](https://user-images.githubusercontent.com/8527588/197228763-87474f16-073f-4343-ab8c-552b9cabed89.jpg)
