### ISSUE TITLE
Support jumping to Weekly and Monthly notes

### ISSUE THREAD

**Issue by wenlzhang** [TfTHacker/obsidian42-jump-to-date#2]
Beside Daily notes, is it possible to jump to Weekly and Monthly notes, like what one can do from the Calendar plugin?

**Comment by TfTHacker** [comment]
Thank you for the idea submission. But I am not planning to add weekly or monthly notes.

**Comment by freyquency** [comment]
oof I was coming here to ask exactly this. Please reconsider.
