### ISSUE TITLE
Slight offset on the interface with Yin-and-Yang theme

### ISSUE THREAD

**Issue by HybridRbt** [TfTHacker/obsidian42-jump-to-date#3]
<img width="315" alt="截屏2021-09-03 下午3 52 34" src="https://user-images.githubusercontent.com/6162974/132064639-5e3a13a2-27bf-4f97-aa54-5d3c0e916c8a.png">

I have also tested with the default theme, Atom, and California Coast. All of them are fine except Yin-and-Yang.

**Comment by TfTHacker** [comment]
I will be doing a style update and hopefully this looks better. I use this theme as well.

**Comment by TfTHacker** [comment]
So the update did not fix this, it is something specific to the them. But this CSS Snippet improves it:

```
.flatpickr-current-month {
  padding: 0 0 0 0 !important;
}
```
