### ISSUE TITLE
Support date formats

### ISSUE THREAD

**Issue by zsviczian** [TfTHacker/obsidian42-jump-to-date#4]
This looks great!
I am using `YYYY-MM-DD dddd` as my daily notes date format. Would be great if you added support for specifying the date format in settings.

**Comment by zsviczian** [comment]
I take that back. Clearly, I didn't have enough sleep. It works great, I was just clicking on a day that didn't yet have a daily note and was prompted by the plugin :)

**Comment by boksir** [comment]
I am facing the same issue with Jump-to-Date: Natural Language date. (JTD:NLD)
I use the `YYYY-MM-DD dddd` format. 
The Jump-to-date: Date picker works fine. 
However when I use **JTD:NLD**, I get an Invalid Date error. 
I tried it on another vault with the date format as `YYYY-MM-DD`, and the JTD:NLD works fine there.

Any thoughts / suggestions?
