### ISSUE TITLE
Incorrect Date used for NLP

### ISSUE THREAD

**Issue by piotryordanov** [TfTHacker/obsidian42-jump-to-date#5]
When I try using natural language, it takes me to this format which si not compatible with my daily notes.
While the non NLP calendar works properly.
Any idea why?
I should open `2021-09-15` without the rest of it.
![image](https://user-images.githubusercontent.com/48773775/133516714-ef543901-6599-415c-a958-7557dae9e811.png)

**Comment by loopernow** [comment]
Check your Natural Language Dates plugin settings. The first setting is the format for the parsed dates.

![image](https://user-images.githubusercontent.com/11263913/133651539-36fa2f55-a020-41a8-8193-10aeb87dcf07.png)

**Comment by piotryordanov** [comment]
That totally fixed it. I had a hunch it was due to another plugin, so i looked at all my cal plugins, but didn't think of the NL dates one.

You are a hero who just made my day :)
