### ISSUE TITLE
Recognition of days in the upcoming week other than the first day?

### ISSUE THREAD

**Issue by loopernow** [TfTHacker/obsidian42-jump-to-date#6]
Just installed this plugin and I quite like it. However, I was wondering if there's any way it can handle dates beyond the current week, other than "next week" and "next month"?

Today's a Thursday and I tried to generate a note for next Sunday (e.g. ten days from now) but when I put "next Sunday" it thinks I'm referring to three days from now instead of ten days from now. I tried "2nd sunday" or "ten days" and it either thinks I mean three days from now or just can't parse what I'm saying, respectively.

Of course, "next Sunday" would be ideal, followed closely by "2nd sunday" or "following sunday," with "ten days" being the worst option.

If none of this is possible, that's fine; I was just wondering if this is a bug or rather a limitation.

--

Edit: I figured out I can say "_In_ ten days" and it will know what I mean, but as mentioned above, that's less than ideal (because first I have to figure out how many days later is the day I'm referring to, which goes against the whole point of using natural language in the first place).

**Comment by TfTHacker** [comment]
Thank you for writing. This is a good suggestion. This feature leverages the Natural Language Dates plugin: https://github.com/argenos/nldates-obsidian. So basically whatever they support, this plugin supports. You would need to share this observation with them for any such changes to "ripple" forward into this plugin.

I hope they can address this. Though I think they use another open source library that has its "own way" of handling NLP. The library is here: https://github.com/wanasit/chrono

perhaps looking at this second site will give you some insight into the logic.

Warm regards!
