### ISSUE TITLE
Date format support for Jump-to-Date: Natural Language date

### ISSUE THREAD

**Issue by boksir** [TfTHacker/obsidian42-jump-to-date#7]
I am facing the same issue with Jump-to-Date: Natural Language date. (JTD:NLD)
I use the `YYYY-MM-DD dddd` format. 
The Jump-to-date: Date picker works fine. 
However when I use **JTD:NLD**, I get an Invalid Date error. 
I tried it on another vault with the date format as `YYYY-MM-DD`, and the JTD:NLD works fine there.

Any thoughts / suggestions?

_Originally posted by @boksir in https://github.com/TfTHacker/obsidian42-jump-to-date/issues/4#issuecomment-924670469_

**Comment by TfTHacker** [comment]
Thank  you for reporting this. I will be pushing out an update today, 1.0.7 and I hope it will fix this problem. To be honest I could not reproduce the problem, but I am also running with the most current support libraries. So it could be this problem was fixed with another library. Please test it after the update and let me know if it is resolved.

Warm regards!

**Comment by boksir** [comment]
Thank you. Will check and get back.

best regards!

**Comment by boksir** [comment]
Sorry, I am still getting an error. 
My settings
![image](https://user-images.githubusercontent.com/83220660/134382714-c3055295-172b-44ba-b794-d744c943c4bf.png)
![image](https://user-images.githubusercontent.com/83220660/134382837-4e53eaa2-65fa-4ae5-bbf7-4201abcee503.png)

If I choose JTD - Date Picker - I get no error
![image](https://user-images.githubusercontent.com/83220660/134383185-a014e59b-51ca-4341-9398-ade2b7444033.png)
![image](https://user-images.githubusercontent.com/83220660/134383263-0e1a9c50-8865-469d-9e1a-f49949a6152a.png)

If I use JTD-Natural Language
![image](https://user-images.githubusercontent.com/83220660/134383454-cd712142-802c-4db2-a62d-ac5d8af6f806.png)
![image](https://user-images.githubusercontent.com/83220660/134383524-bb87116a-74b3-40d2-96cf-c93a947d53e9.png)

Haven't been able to figure this out

**Comment by TfTHacker** [comment]
Very odd. I will do some more testing. Thank you for the screen shots too.

Just a questions, is the Natural Language Date plugin working correct when it generates dates?

**Comment by TfTHacker** [comment]
I believe I have fixed this now. Can you please do an update in obsidian and test it? If it works, please close out the issue.

**Comment by boksir** [comment]
It works perfectly now!! Thank you! 
Closing the issue.
best regards!

**Comment by boksir** [comment]
Hi, opening this issue again. My date format is YYYY-MM-DD-ddd. 
I get an invalid date error for days from 1st to 9th of the month.. All 2 digit days 10th to 31st work fine. 
Screenshots below
**Single digit Day**
![image](https://user-images.githubusercontent.com/83220660/135246034-3176fd76-eec3-453d-9c28-604d9c169d7c.png)
![image](https://user-images.githubusercontent.com/83220660/135246331-052d16c0-59fa-48a3-94ca-8a5c702f2891.png)
Maybe the error is it shows 2021-10-4, instead of 2021-10-04??
![image](https://user-images.githubusercontent.com/83220660/135246518-8fdb7a0c-f4f1-4869-ab40-1d1e151aad89.png)

**2 Digit Day**
![image](https://user-images.githubusercontent.com/83220660/135246891-7a8d773d-304c-4579-85b8-7f5c26bfa98c.png)
![image](https://user-images.githubusercontent.com/83220660/135247160-1f02cc5a-303e-4ef5-b355-7ffcc562cadb.png)
![image](https://user-images.githubusercontent.com/83220660/135247237-e80d0573-9d3f-4f54-b91a-e8a0f64c18d4.png)

This error happens for existing dates as well, which are already created. It does not see them as created
**Already Created Date**
![image](https://user-images.githubusercontent.com/83220660/135247548-b917af5c-a8d3-4a3d-880a-f5989d3441ee.png)
![image](https://user-images.githubusercontent.com/83220660/135247670-8f84967e-ee58-44c9-8810-1bc995c1cd86.png)
**It says the date does not exist**
![image](https://user-images.githubusercontent.com/83220660/135247784-393a4203-0962-4de2-9d69-9290db804e7f.png)

**Comment by boksir** [comment]
Closing this as I opened a separate issue for this as I felt the issue was slightly different
