### ISSUE TITLE
Invalid Date Error for single digit days - Natural Language Date

### ISSUE THREAD

**Issue by boksir** [TfTHacker/obsidian42-jump-to-date#9]
Hi,. My date format is YYYY-MM-DD-ddd. 
I get an invalid date error for days from 1st to 9th of the month.. All 2 digit days 10th to 31st work fine. 
Screenshots below
**Single digit Day**
![image](https://user-images.githubusercontent.com/83220660/135246034-3176fd76-eec3-453d-9c28-604d9c169d7c.png)
![image](https://user-images.githubusercontent.com/83220660/135246331-052d16c0-59fa-48a3-94ca-8a5c702f2891.png)
Maybe the error is it shows 2021-10-4, instead of 2021-10-04??
![image](https://user-images.githubusercontent.com/83220660/135246518-8fdb7a0c-f4f1-4869-ab40-1d1e151aad89.png)

**2 Digit Day**
![image](https://user-images.githubusercontent.com/83220660/135246891-7a8d773d-304c-4579-85b8-7f5c26bfa98c.png)
![image](https://user-images.githubusercontent.com/83220660/135247160-1f02cc5a-303e-4ef5-b355-7ffcc562cadb.png)
![image](https://user-images.githubusercontent.com/83220660/135247237-e80d0573-9d3f-4f54-b91a-e8a0f64c18d4.png)

This error happens for existing dates as well, which are already created. It does not see them as created
**Already Created Date**
![image](https://user-images.githubusercontent.com/83220660/135247548-b917af5c-a8d3-4a3d-880a-f5989d3441ee.png)
![image](https://user-images.githubusercontent.com/83220660/135247670-8f84967e-ee58-44c9-8810-1bc995c1cd86.png)
**It says the date does not exist**
![image](https://user-images.githubusercontent.com/83220660/135247784-393a4203-0962-4de2-9d69-9290db804e7f.png)

**Comment by TfTHacker** [comment]
This will be fixed with a 1.0.10 update that I will push out here shortly.
